#!/usr/bin/env bash


# 引入配置文件
# read config file
source ./vendor/cul8r/php-codesat/phpsat.ini

# 检查phplint的命令路径是否配置
# 如果没有配置,则使用默认的路径
# 如果配置了,则进一步检查配置的路径是否正确
# check if phplint_path is config
if [[ x"$phplint_path" = x ]]; then
    phplint_path="./vendor/bin/phplint"
else
    ${phplint_path} --version > /dev/null
    if [[ $? -ne 0 ]]; then
        echo "Command phplint error, please check it and retry~"
        exit 1
    fi
fi

# 检查phpstan的命令路径是否配置
# 如果没有配置,则使用默认的路径
# 如果配置了,则进一步检查配置的路径是否正确
# check if phpstan_path is config
if [[ x"$phpstan_path" = x ]]; then
    phpstan_path="phpstan"
else
    ${phpstan_path} --version > /dev/null
    if [[ $? -ne 0 ]]; then
        echo "Command phpstan error, please check it and retry~"
        exit 1
    fi
fi

# 获取本次提交的差异文件
a=`git status -s`

array=(${a//,/ })
for var in ${array[@]}
do
    if [[ "$var" = "M" ]] || [[ "$var" = "A" ]] || [[ "$var" = "D" ]]; then
        continue
    fi

    # check php file
    if [[ ! ${var} =~ ".php" ]]; then
        echo "Check file $var: not php file, ignoring..."
        continue
    fi

    # phplint
    if [[ ${phplint} == "true" ]]; then
        phplintResult=`${phplint_path} $var | grep error`
        if [[ x"$phplintResult" != x ]]; then
            echo -e "\033[43;34m ---------------PHPLINT ERROR-----------------------------:\033[0m \n"
            ${phplint_path} ${var} | while read line
            do
                echo ${line}
            done
            askContinue
            exit 1
        else
            echo -e "\033[5;31m phplint file [$var] success \n\n\n \033[0m"
        fi
    fi

echo -e "\033[42;34m PHPSTAN CHECK START \n  \033[0m"
echo -e "\n"

    # phpstan
    if [[ ${phpstan} == "true" ]]; then
        phpstanResult=`${phpstan_path} analyse --memory-limit=1G --configuration=phpstan.neon ${var} | grep Line`
        if [[ x"$phpstanResult" != x ]]; then
            echo -e "\033[41;30m ---------PHPSTAN ERROR------------:\033[0m \n"

            ${phpstan_path} analyse --memory-limit=1G --configuration=phpstan.neon ${var} | while read line
            do
                echo ${line}
            done
                echo -e "\033[42;34m PHPSTAN CHECK END \n  \033[0m"
            #askContinue
            exit 1
        else
            echo -e "\033[5;31m phpstan file [$var] success \033[0m"
        fi
    fi
done

echo -e "\033[5;31m check success,commit success \033[0m"
exit 0
